apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: mohsen51/hardened-webapp:1.0.0
          ports:
            - containerPort: 8080
          securityContext:
            # Run non-root
            privileged: false
            # Disallow switch user
            allowPrivilegeEscalation: false
            
            # Drop all capabilities
            capabilities:
              drop:
                - ALL
